name: "TruffleHog"
description: "Run TruffleHog in current branch context"
inputs:
  path:
    required: true
    description: Repository path
  branch:
    required: true
    description: Start scanning from here (usually main).
  version:
    required: false
    description: Witch version of TruffleHog will be used.
    default: latest
  extra:
    required: false
    description: Extra args to be passed to the trufflehog cli.
    default: ''
branding:
  icon: "shield"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - git
    - file://${{ inputs.path }}
    - --branch
    - ${{ inputs.branch }}
    - --fail
    - ${{ inputs.extra }}