name: "TruffleHog"
description: "Run TruffleHog in current branch context"
inputs:
  path:
    description: Repository path
    required: true
  branch:
    description: Start scanning from here (usually main).
    required: true
  head:
    description: Scan commits until here (usually dev branch).
    required: false
    default: ''
  extra:
    required: false
    default: ''
    description: Extra args to be passed to the trufflehog cli.
branding:
  icon: "shield"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - git
    - file://${{ inputs.path }}
    - --branch
    - ${{ inputs.branch }}
    - --since-commit
    - ${{ inputs.head }}
    - --fail
    - ${{ inputs.extra }}