on: [push]

jobs:
  code-scan:
    runs-on: ubuntu-latest
    name: security-tooling
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Check for hardcoded secrets
        uses: 6a6f6a6f/action@main
        with:
          version: v3.7.0
          path: ./
          branch: ${{ github.event.repository.default_branch }}
